[theme]
base = "light"
primaryColor = "#284f3e"
backgroundColor = "#f7f8f2"
secondaryBackgroundColor = "#edf0e5"
textColor = "#183e33"
font = "sans-serif"

[server]
headless = true

[browser]
gatherUsageStats = false
